io:
  queueSize: 2048
  queueNum: 100
  table: opengfw
  connMarkAccept: 1001
  connMarkDrop: 1002
  rcvBuf: 4194304
  sndBuf: 4194304
  local: true
  rst: false

workers:
  count: 2
  queueSize: 32
  tcpMaxBufferedPagesTotal: 24576
  tcpMaxBufferedPagesPerConn: 8
  tcpTimeout: 2m
  udpMaxStreams: 2048

replay:
  realtime: false
